import {
  AlertTriangleIcon,
  CalendarIcon,
  ChartBarIcon,
  ClipboardIcon,
  ClockIcon,
  CreditCardIcon,
  DocumentIcon,
  DownloadIcon,
  FactoryIcon,
  GaugeIcon,
  HomeIcon,
  LockIcon,
  MapPinIcon,
  MessageIcon,
  SendIcon,
  SettingsIcon,
  ShieldCheckIcon,
  TankIcon,
  TrendingUpIcon,
  TruckIcon,
  UsersIcon,
  WalletIcon,
} from "@/components/icons";
import type { RoleSlug } from "@/lib/roles";

/**
 * `roles` restricts a nav item to the given roles. Omit it to show the item
 * to every role (this is how the Company Owner keeps the full, unchanged nav).
 */
export const DASHBOARD_NAV = [
  { href: "/dashboard", label: "Overview", icon: HomeIcon },
  {
    href: "/dashboard/pumps",
    label: "Pumps",
    icon: GaugeIcon,
    roles: ["company-owner", "company-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/fuel-stock",
    label: "Fuel Stock",
    icon: TankIcon,
    roles: ["company-owner", "company-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/tanker-fleet",
    label: "Tanker Fleet & Live Tracking",
    icon: TruckIcon,
    roles: ["company-owner", "company-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/tanker-deliveries",
    label: "Tanker Delivery Logs",
    icon: ClipboardIcon,
    roles: ["company-owner", "company-manager"] as RoleSlug[],
  },
  { href: "/dashboard/pump-owners", label: "Pump Owners & Payments", icon: CreditCardIcon },
  {
    href: "/dashboard/chat",
    label: "Live Chat",
    icon: MessageIcon,
    roles: ["company-owner"] as RoleSlug[],
  },
  { href: "/dashboard/employees", label: "Employees & Attendance", icon: UsersIcon },
  {
    href: "/dashboard/access-control",
    label: "Custom Access Control",
    icon: LockIcon,
    roles: ["company-owner"] as RoleSlug[],
  },
  {
    href: "/dashboard/finance",
    label: "Finance",
    icon: WalletIcon,
    roles: ["company-owner", "finance-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/fuel-prices",
    label: "Live Fuel Prices",
    icon: TrendingUpIcon,
    roles: ["company-owner", "company-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/hr/employees",
    label: "Company Employees",
    icon: UsersIcon,
    roles: ["company-owner", "hr-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/hr/departments",
    label: "Departments",
    icon: FactoryIcon,
    roles: ["company-owner", "hr-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/hr/attendance",
    label: "Attendance",
    icon: ClockIcon,
    roles: ["company-owner", "hr-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/hr/shifts",
    label: "Shifts",
    icon: CalendarIcon,
    roles: ["company-owner", "hr-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/hr/leave",
    label: "Leave",
    icon: ClipboardIcon,
    roles: ["company-owner", "hr-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/hr/payroll",
    label: "Payroll Coordination",
    icon: CreditCardIcon,
    roles: ["company-owner", "hr-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/depot/stock",
    label: "Depot Stock",
    icon: TankIcon,
    roles: ["company-owner", "depot-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/depot/receiving",
    label: "Petrol/Diesel Receiving",
    icon: DownloadIcon,
    roles: ["company-owner", "depot-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/depot/distribution",
    label: "Stock Distribution",
    icon: TruckIcon,
    roles: ["company-owner", "depot-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/depot/remaining",
    label: "Remaining Stock",
    icon: GaugeIcon,
    roles: ["company-owner", "depot-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/logistics/tanker-fleet",
    label: "Tanker Fleet",
    icon: TruckIcon,
    roles: ["logistics-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/logistics/drivers",
    label: "Drivers",
    icon: UsersIcon,
    roles: ["logistics-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/logistics/routes",
    label: "Routes",
    icon: MapPinIcon,
    roles: ["logistics-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/logistics/dispatch",
    label: "Dispatch",
    icon: SendIcon,
    roles: ["logistics-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/logistics/live-tracking",
    label: "Live Tracking",
    icon: GaugeIcon,
    roles: ["logistics-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/logistics/delivery-records",
    label: "Delivery Records",
    icon: ClipboardIcon,
    roles: ["logistics-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/sales/pump-wise",
    label: "Pump-wise Sales",
    icon: GaugeIcon,
    roles: ["company-owner", "sales-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/sales/performance",
    label: "Sales Performance",
    icon: TrendingUpIcon,
    roles: ["company-owner", "sales-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/sales/periodic",
    label: "Daily/Weekly/Monthly Sales",
    icon: CalendarIcon,
    roles: ["company-owner", "sales-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/sales/reports",
    label: "Sales Reports",
    icon: DocumentIcon,
    roles: ["company-owner", "sales-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/admin/users",
    label: "System Users",
    icon: UsersIcon,
    roles: ["company-owner", "it-admin"] as RoleSlug[],
  },
  {
    href: "/dashboard/admin/permissions",
    label: "Permissions",
    icon: ShieldCheckIcon,
    roles: ["company-owner", "it-admin"] as RoleSlug[],
  },
  {
    href: "/dashboard/admin/settings",
    label: "Technical Settings",
    icon: SettingsIcon,
    roles: ["company-owner", "it-admin"] as RoleSlug[],
  },
  {
    href: "/dashboard/admin/access",
    label: "User Access",
    icon: LockIcon,
    roles: ["company-owner", "it-admin"] as RoleSlug[],
  },
  {
    href: "/dashboard/area/pumps-overview",
    label: "Assigned Pumps Overview",
    icon: MapPinIcon,
    roles: ["company-owner", "area-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/area/visits",
    label: "Pump Visits & Performance",
    icon: ChartBarIcon,
    roles: ["company-owner", "area-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/area/coordination",
    label: "Coordination",
    icon: MessageIcon,
    roles: ["company-owner", "area-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/area/escalations",
    label: "Issue Escalation",
    icon: AlertTriangleIcon,
    roles: ["company-owner", "area-manager"] as RoleSlug[],
  },
  { href: "/dashboard/reports", label: "Reports", icon: DocumentIcon },
] as const;
