import {
  AlertTriangleIcon,
  CalendarIcon,
  ChartBarIcon,
  CheckCircleIcon,
  ClipboardIcon,
  ClockIcon,
  CreditCardIcon,
  DocumentIcon,
  DownloadIcon,
  DropletIcon,
  FactoryIcon,
  FlaskIcon,
  GaugeIcon,
  HomeIcon,
  LockIcon,
  MapPinIcon,
  MessageIcon,
  SendIcon,
  SettingsIcon,
  ShieldCheckIcon,
  TankIcon,
  TrendingUpIcon,
  TruckIcon,
  UsersIcon,
  WalletIcon,
} from "@/components/icons";
import type { RoleSlug } from "@/lib/roles";

/**
 * `roles` restricts a nav item to the given roles. Omit it to show the item
 * to every role (this is how the Company Owner keeps the full, unchanged nav).
 */
export const DASHBOARD_NAV = [
  { href: "/dashboard", label: "Overview", icon: HomeIcon },
  {
    href: "/dashboard/pumps",
    label: "Pumps",
    icon: GaugeIcon,
    roles: ["company-owner", "company-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/fuel-stock",
    label: "Fuel Stock",
    icon: TankIcon,
    roles: ["company-owner", "company-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/tanker-fleet",
    label: "Tanker Fleet & Live Tracking",
    icon: TruckIcon,
    roles: ["company-owner", "company-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/tanker-deliveries",
    label: "Tanker Delivery Logs",
    icon: ClipboardIcon,
    roles: ["company-owner", "company-manager"] as RoleSlug[],
  },
  { href: "/dashboard/pump-owners", label: "Pump Owners & Payments", icon: CreditCardIcon },
  {
    href: "/dashboard/chat",
    label: "Live Chat",
    icon: MessageIcon,
    roles: ["company-owner"] as RoleSlug[],
  },
  { href: "/dashboard/employees", label: "Employees & Attendance", icon: UsersIcon },
  {
    href: "/dashboard/access-control",
    label: "Custom Access Control",
    icon: LockIcon,
    roles: ["company-owner"] as RoleSlug[],
  },
  {
    href: "/dashboard/finance",
    label: "Finance",
    icon: WalletIcon,
    roles: ["company-owner", "finance-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/fuel-prices",
    label: "Live Fuel Prices",
    icon: TrendingUpIcon,
    roles: ["company-owner", "company-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/hr/employees",
    label: "Company Employees",
    icon: UsersIcon,
    roles: ["company-owner", "hr-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/hr/departments",
    label: "Departments",
    icon: FactoryIcon,
    roles: ["company-owner", "hr-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/hr/attendance",
    label: "Attendance",
    icon: ClockIcon,
    roles: ["company-owner", "hr-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/hr/shifts",
    label: "Shifts",
    icon: CalendarIcon,
    roles: ["company-owner", "hr-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/hr/leave",
    label: "Leave",
    icon: ClipboardIcon,
    roles: ["company-owner", "hr-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/hr/payroll",
    label: "Payroll Coordination",
    icon: CreditCardIcon,
    roles: ["company-owner", "hr-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/depot/stock",
    label: "Depot Stock",
    icon: TankIcon,
    roles: ["company-owner", "depot-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/depot/receiving",
    label: "Petrol/Diesel Receiving",
    icon: DownloadIcon,
    roles: ["company-owner", "depot-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/depot/distribution",
    label: "Stock Distribution",
    icon: TruckIcon,
    roles: ["company-owner", "depot-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/depot/remaining",
    label: "Remaining Stock",
    icon: GaugeIcon,
    roles: ["company-owner", "depot-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/depot/fuel-stock-management",
    label: "Fuel Stock Management",
    icon: TankIcon,
    roles: ["company-owner", "depot-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/depot/loading-oversight",
    label: "Tanker Loading Oversight",
    icon: TruckIcon,
    roles: ["company-owner", "depot-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/depot/quantity-verification",
    label: "Loaded Quantity Verification",
    icon: CheckCircleIcon,
    roles: ["company-owner", "depot-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/logistics/tanker-fleet",
    label: "Tanker Fleet",
    icon: TruckIcon,
    roles: ["logistics-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/logistics/drivers",
    label: "Drivers",
    icon: UsersIcon,
    roles: ["logistics-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/logistics/routes",
    label: "Routes",
    icon: MapPinIcon,
    roles: ["logistics-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/logistics/dispatch",
    label: "Dispatch",
    icon: SendIcon,
    roles: ["logistics-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/logistics/live-tracking",
    label: "Live Tracking",
    icon: GaugeIcon,
    roles: ["logistics-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/logistics/delivery-records",
    label: "Delivery Records",
    icon: ClipboardIcon,
    roles: ["logistics-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/sales/pump-wise",
    label: "Pump-wise Sales",
    icon: GaugeIcon,
    roles: ["company-owner", "sales-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/sales/performance",
    label: "Sales Performance",
    icon: TrendingUpIcon,
    roles: ["company-owner", "sales-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/sales/periodic",
    label: "Daily/Weekly/Monthly Sales",
    icon: CalendarIcon,
    roles: ["company-owner", "sales-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/sales/reports",
    label: "Sales Reports",
    icon: DocumentIcon,
    roles: ["company-owner", "sales-manager"] as RoleSlug[],
  },
  {
    href: "/admin/pumps",
    label: "Pump Management",
    icon: GaugeIcon,
    roles: ["admin"] as RoleSlug[],
  },
  {
    href: "/admin/employees",
    label: "Employee Management",
    icon: UsersIcon,
    roles: ["admin"] as RoleSlug[],
  },
  {
    href: "/admin/pump-owner-requests",
    label: "Pump Owner Approvals",
    icon: CheckCircleIcon,
    roles: ["admin"] as RoleSlug[],
  },
  {
    href: "/admin/signup-requests",
    label: "Employee Approvals",
    icon: CheckCircleIcon,
    roles: ["admin"] as RoleSlug[],
  },
  {
    href: "/admin/role-create",
    label: "Create Company Roles",
    icon: UsersIcon,
    roles: ["admin"] as RoleSlug[],
  },
  {
    href: "/dashboard/admin/users",
    label: "System Users",
    icon: UsersIcon,
    roles: ["company-owner", "it-admin"] as RoleSlug[],
  },
  {
    href: "/dashboard/admin/permissions",
    label: "Permissions",
    icon: ShieldCheckIcon,
    roles: ["company-owner", "it-admin"] as RoleSlug[],
  },
  {
    href: "/dashboard/admin/settings",
    label: "Technical Settings",
    icon: SettingsIcon,
    roles: ["company-owner", "it-admin"] as RoleSlug[],
  },
  {
    href: "/dashboard/admin/access",
    label: "User Access",
    icon: LockIcon,
    roles: ["company-owner", "it-admin"] as RoleSlug[],
  },
  {
    href: "/dashboard/area/pumps-overview",
    label: "Assigned Pumps Overview",
    icon: MapPinIcon,
    roles: ["company-owner", "area-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/area/visits",
    label: "Pump Visits & Performance",
    icon: ChartBarIcon,
    roles: ["company-owner", "area-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/area/coordination",
    label: "Coordination",
    icon: MessageIcon,
    roles: ["company-owner", "area-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/area/escalations",
    label: "Issue Escalation",
    icon: AlertTriangleIcon,
    roles: ["company-owner", "area-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/depot-staff/load-tankers",
    label: "Load Fuel into Tankers",
    icon: TruckIcon,
    roles: ["company-owner", "depot-staff"] as RoleSlug[],
  },
  {
    href: "/dashboard/depot-staff/loading-log",
    label: "Record Loading Quantity & Time",
    icon: ClockIcon,
    roles: ["company-owner", "depot-staff"] as RoleSlug[],
  },
  {
    href: "/dashboard/depot-staff/stock-report",
    label: "Report Depot Stock Levels",
    icon: TankIcon,
    roles: ["company-owner", "depot-staff"] as RoleSlug[],
  },
  {
    href: "/dashboard/dispatch/schedule-trips",
    label: "Schedule Tanker Trips",
    icon: CalendarIcon,
    roles: ["company-owner", "dispatch-officer"] as RoleSlug[],
  },
  {
    href: "/dashboard/dispatch/assign-driver-pump",
    label: "Assign Driver & Destination Pump",
    icon: UsersIcon,
    roles: ["company-owner", "dispatch-officer"] as RoleSlug[],
  },
  {
    href: "/dashboard/dispatch/track-departure-arrival",
    label: "Track Departure & Confirm Arrival",
    icon: TruckIcon,
    roles: ["company-owner", "dispatch-officer"] as RoleSlug[],
  },
  {
    href: "/dashboard/quality/fuel-testing",
    label: "Fuel Quality Testing",
    icon: FlaskIcon,
    roles: ["company-owner", "quality-control-officer"] as RoleSlug[],
  },
  {
    href: "/dashboard/quality/adulteration-checks",
    label: "Adulteration Checks",
    icon: ShieldCheckIcon,
    roles: ["company-owner", "quality-control-officer"] as RoleSlug[],
  },
  {
    href: "/dashboard/quality/inspection-log",
    label: "Log Inspection Results",
    icon: ClipboardIcon,
    roles: ["company-owner", "quality-control-officer"] as RoleSlug[],
  },
  {
    href: "/dashboard/driver/schedule",
    label: "Trip Schedule",
    icon: CalendarIcon,
    roles: ["company-owner", "tanker-driver"] as RoleSlug[],
  },
  {
    href: "/dashboard/driver/departure-arrival",
    label: "Log Departure & Arrival",
    icon: ClockIcon,
    roles: ["company-owner", "tanker-driver"] as RoleSlug[],
  },
  {
    href: "/dashboard/driver/fuel-log",
    label: "Fuel Loaded/Unloaded",
    icon: DropletIcon,
    roles: ["company-owner", "tanker-driver"] as RoleSlug[],
  },
  {
    href: "/dashboard/driver/delivery-confirmation",
    label: "Route & Delivery Confirmation",
    icon: CheckCircleIcon,
    roles: ["company-owner", "tanker-driver"] as RoleSlug[],
  },
  {
    href: "/dashboard/accounts/payments",
    label: "Company-level Payment Processing",
    icon: WalletIcon,
    roles: ["company-owner", "accounts-officer"] as RoleSlug[],
  },
  {
    href: "/dashboard/accounts/invoicing",
    label: "Invoicing",
    icon: DocumentIcon,
    roles: ["company-owner", "accounts-officer"] as RoleSlug[],
  },
  {
    href: "/dashboard/accounts/pump-owner-ledger",
    label: "Pump Owner Ledger",
    icon: CreditCardIcon,
    roles: ["company-owner", "accounts-officer"] as RoleSlug[],
  },
  {
    href: "/dashboard/hr-officer/employee-records",
    label: "Employee Records",
    icon: UsersIcon,
    roles: ["company-owner", "hr-officer"] as RoleSlug[],
  },
  {
    href: "/dashboard/hr-officer/attendance-payroll",
    label: "Attendance & Payroll Processing",
    icon: ClockIcon,
    roles: ["company-owner", "hr-officer"] as RoleSlug[],
  },
  { href: "/dashboard/reports", label: "Reports", icon: DocumentIcon },
  {
    href: "/dashboard/attendant",
    label: "Attendant Overview",
    icon: HomeIcon,
    roles: ["pump-attendant"] as RoleSlug[],
  },
  {
    href: "/dashboard/attendant/dispense",
    label: "Dispense Fuel",
    icon: DropletIcon,
    roles: ["pump-attendant"] as RoleSlug[],
  },
  {
    href: "/dashboard/attendant/history",
    label: "Shift History",
    icon: ClockIcon,
    roles: ["pump-attendant"] as RoleSlug[],
  },
  {
    href: "/dashboard/cashier",
    label: "Cashier Overview",
    icon: HomeIcon,
    roles: ["cashier"] as RoleSlug[],
  },
  {
    href: "/dashboard/cashier/collect",
    label: "Collect Payment",
    icon: WalletIcon,
    roles: ["cashier"] as RoleSlug[],
  },
  {
    href: "/dashboard/cashier/history",
    label: "Shift History",
    icon: ClockIcon,
    roles: ["cashier"] as RoleSlug[],
  },
  {
    href: "/dashboard/cashier/reports",
    label: "Cash Reports",
    icon: DocumentIcon,
    roles: ["cashier"] as RoleSlug[],
  },
  {
    href: "/dashboard/pump-owner",
    label: "My Pump Overview",
    icon: HomeIcon,
    roles: ["pump-owner"] as RoleSlug[],
  },
  {
    href: "/dashboard/pump-owner/fuel-price",
    label: "Live Fuel Price",
    icon: TrendingUpIcon,
    roles: ["pump-owner"] as RoleSlug[],
  },
  {
    href: "/dashboard/pump-owner/fuel-stock",
    label: "My Fuel Stock",
    icon: TankIcon,
    roles: ["pump-owner"] as RoleSlug[],
  },
  {
    href: "/dashboard/pump-owner/sales",
    label: "My Sales",
    icon: GaugeIcon,
    roles: ["pump-owner"] as RoleSlug[],
  },
  {
    href: "/dashboard/pump-owner/staff",
    label: "My Staff",
    icon: UsersIcon,
    roles: ["pump-owner"] as RoleSlug[],
  },
  {
    href: "/dashboard/pump-owner/tankers",
    label: "Incoming Tankers",
    icon: TruckIcon,
    roles: ["pump-owner"] as RoleSlug[],
  },
  {
    href: "/dashboard/pump-owner/payments",
    label: "Payments to Company",
    icon: CreditCardIcon,
    roles: ["pump-owner"] as RoleSlug[],
  },
  {
    href: "/dashboard/pump-owner/reports",
    label: "Reports",
    icon: DocumentIcon,
    roles: ["pump-owner"] as RoleSlug[],
  },
  {
    href: "/dashboard/pump-manager",
    label: "Pump Overview",
    icon: HomeIcon,
    roles: ["pump-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/pump-manager/staff",
    label: "Staff & Shifts",
    icon: UsersIcon,
    roles: ["pump-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/pump-manager/attendance",
    label: "Attendance",
    icon: ClockIcon,
    roles: ["pump-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/pump-manager/fuel-stock",
    label: "Fuel Stock",
    icon: TankIcon,
    roles: ["pump-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/pump-manager/sales",
    label: "Daily Sales",
    icon: GaugeIcon,
    roles: ["pump-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/pump-manager/tankers",
    label: "Incoming Tankers",
    icon: TruckIcon,
    roles: ["pump-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/pump-manager/reports",
    label: "Reports",
    icon: DocumentIcon,
    roles: ["pump-manager"] as RoleSlug[],
  },
  {
    href: "/dashboard/maintenance",
    label: "Maintenance Overview",
    icon: HomeIcon,
    roles: ["maintenance-technician"] as RoleSlug[],
  },
  {
    href: "/dashboard/maintenance/pumps",
    label: "Assigned Pumps",
    icon: GaugeIcon,
    roles: ["maintenance-technician"] as RoleSlug[],
  },
  {
    href: "/dashboard/maintenance/issues",
    label: "Maintenance Issues",
    icon: AlertTriangleIcon,
    roles: ["maintenance-technician"] as RoleSlug[],
  },
  {
    href: "/dashboard/maintenance/repairs",
    label: "Repair Tracking",
    icon: ClipboardIcon,
    roles: ["maintenance-technician"] as RoleSlug[],
  },
  {
    href: "/dashboard/maintenance/history",
    label: "Repair History",
    icon: ClockIcon,
    roles: ["maintenance-technician"] as RoleSlug[],
  },
  {
    href: "/dashboard/maintenance/schedule",
    label: "Schedule Maintenance",
    icon: CalendarIcon,
    roles: ["maintenance-technician"] as RoleSlug[],
  },
] as const;
